-- Apply to a NEW Supabase project, never over the legacy database.
begin;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
create table public.profiles (
 id uuid primary key references auth.users on delete cascade,
 full_name text not null default '', school_name text not null default '',
 mobile_number text not null default '', city text not null default '',
 dob date, gender text not null default '', state text not null default '', country text not null default '',
 role text not null default 'student' check (role in ('student','admin')),
 created_at timestamptz not null default now()
);
create function private.create_profile() returns trigger language plpgsql security definer set search_path = '' as $$
begin insert into public.profiles(id,full_name,school_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.raw_user_meta_data->>'school_name','')); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.create_profile();
create function public.is_admin() returns boolean language sql stable security definer set search_path = '' as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;
create table public.exams (id text primary key, slug text unique not null, name text not null, description text not null, subjects text[] not null default '{}', status text not null default 'active' check(status in ('active','coming_soon')), sort_order int not null default 0);
create table public.tests (
 id bigint generated by default as identity primary key, exam_id text not null references public.exams,
 test_name text not null, duration_minutes int not null check(duration_minutes between 1 and 360),
 subject_topic text not null default '', instructions text not null default '',
 test_category text not null default 'standard' check(test_category in ('standard','demo','upcoming')),
 date_scheduled timestamptz, published boolean not null default false, created_at timestamptz not null default now()
);
create table public.questions (
 id bigint generated by default as identity primary key, test_id bigint not null references public.tests on delete cascade,
 question_text text not null, options jsonb not null check(jsonb_typeof(options)='object' and options ?& array['a','b','c','d']),
 correct_option text not null check(correct_option in ('a','b','c','d')), marks int not null default 1 check(marks between 1 and 100), image_url text
);
create index questions_test_id_idx on public.questions(test_id);
create table public.bundles (id bigint generated by default as identity primary key, exam_id text not null references public.exams, bundle_name text not null, description text not null default '', price numeric(10,2) not null default 0 check(price>=0), features text[] not null default '{}', published boolean not null default false);
create table public.bundle_tests (bundle_id bigint references public.bundles on delete cascade, test_id bigint references public.tests on delete cascade, primary key(bundle_id,test_id));
create table public.enrollments (user_id uuid references public.profiles on delete cascade, test_id bigint references public.tests on delete cascade, created_at timestamptz not null default now(), primary key(user_id,test_id));
create table private.attempts (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade,
 test_id bigint not null references public.tests, started_at timestamptz not null default now(), ends_at timestamptz not null,
 snapshot jsonb not null, answers jsonb not null default '{}', submitted_at timestamptz
);
create unique index one_open_attempt on private.attempts(user_id,test_id) where submitted_at is null;
create table public.results (
 id uuid primary key references private.attempts on delete cascade, user_id uuid not null references public.profiles on delete cascade,
 test_id bigint not null references public.tests, score int not null, total_marks int not null,
 correct_count int not null, question_count int not null, submitted_at timestamptz not null default now()
);
create index results_user_id_idx on public.results(user_id);
alter table public.profiles enable row level security;
alter table public.exams enable row level security;
alter table public.tests enable row level security;
alter table public.questions enable row level security;
alter table public.bundles enable row level security;
alter table public.bundle_tests enable row level security;
alter table public.enrollments enable row level security;
alter table public.results enable row level security;
create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy profiles_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
-- Column grants prevent users promoting themselves, even through direct REST calls.
revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant update(full_name,school_name,mobile_number,city,dob,gender,state,country) on public.profiles to authenticated;
create policy exams_read on public.exams for select using(true);
create policy exams_admin on public.exams for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy tests_read on public.tests for select using(published or public.is_admin());
create policy tests_admin on public.tests for all to authenticated using(public.is_admin()) with check(public.is_admin());
-- Answer keys never have a student SELECT policy. Students receive a stripped snapshot through start_attempt.
create policy questions_admin on public.questions for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy bundles_read on public.bundles for select using(published or public.is_admin());
create policy bundles_admin on public.bundles for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy bundle_tests_read on public.bundle_tests for select using(exists(select 1 from public.bundles b where b.id=bundle_id and b.published) or public.is_admin());
create policy bundle_tests_admin on public.bundle_tests for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy enrollments_read on public.enrollments for select to authenticated using(user_id=auth.uid() or public.is_admin());
create policy enrollments_admin on public.enrollments for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy results_read on public.results for select to authenticated using(user_id=auth.uid() or public.is_admin());
grant select on public.exams,public.tests,public.bundles,public.bundle_tests to anon,authenticated;
grant select,insert,update,delete on public.exams,public.tests,public.questions,public.bundles,public.bundle_tests,public.enrollments to authenticated;
grant select on public.results to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create function public.start_attempt(p_test_id bigint) returns jsonb language plpgsql security definer set search_path='' as $$
declare t public.tests; a private.attempts; snapshot jsonb; safe_questions jsonb;
begin
 if auth.uid() is null then raise exception 'Please sign in'; end if;
 perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text || ':' || p_test_id::text,0));
 select * into t from public.tests where id=p_test_id and published;
 if not found then raise exception 'Test is unavailable'; end if;
 if t.test_category='upcoming' or t.date_scheduled>now() then raise exception 'This test is not open yet'; end if;
 if t.test_category<>'demo' and not exists(select 1 from public.enrollments where user_id=auth.uid() and test_id=p_test_id) and not public.is_admin() then raise exception 'This test is not assigned to your account'; end if;
 select * into a from private.attempts where user_id=auth.uid() and test_id=p_test_id and submitted_at is null;
 if not found then
  select jsonb_agg(to_jsonb(q) order by q.id) into snapshot from public.questions q where q.test_id=p_test_id;
  if snapshot is null then raise exception 'Questions have not been published yet'; end if;
  insert into private.attempts(user_id,test_id,ends_at,snapshot) values(auth.uid(),p_test_id,now()+make_interval(mins=>t.duration_minutes),snapshot) returning * into a;
 end if;
 select jsonb_agg(q-'correct_option'-'test_id') into safe_questions from jsonb_array_elements(a.snapshot) q;
 return jsonb_build_object('id',a.id,'test_id',a.test_id,'ends_at',a.ends_at,'questions',safe_questions,'answers',a.answers);
end $$;
create function private.valid_answers(snapshot jsonb, answers jsonb) returns boolean language sql immutable set search_path='' as $$
 select jsonb_typeof(answers)='object' and not exists (
 select 1 from jsonb_each_text(answers) entry where not exists (
 select 1 from jsonb_array_elements(snapshot) q where q->>'id'=entry.key and (q->'options') ? entry.value))
$$;
create function public.save_answers(p_attempt_id uuid,p_answers jsonb) returns void language plpgsql security definer set search_path='' as $$
declare a private.attempts;
begin
 select * into a from private.attempts where id=p_attempt_id and user_id=auth.uid() for update;
 if not found then raise exception 'Attempt not found'; end if;
 if a.submitted_at is not null or now()>a.ends_at then raise exception 'This attempt has ended'; end if;
 if not private.valid_answers(a.snapshot,p_answers) then raise exception 'Invalid answers'; end if;
 update private.attempts set answers=p_answers where id=a.id;
end $$;
create function public.submit_attempt(p_attempt_id uuid,p_answers jsonb) returns uuid language plpgsql security definer set search_path='' as $$
declare a private.attempts; q jsonb; earned int:=0; total int:=0; correct int:=0;
begin
 select * into a from private.attempts where id=p_attempt_id and user_id=auth.uid() for update;
 if not found then raise exception 'Attempt not found'; end if;
 if a.submitted_at is not null then return a.id; end if;
 -- After expiry only answers already saved before the server deadline are scored.
 if now()<=a.ends_at then
  if not private.valid_answers(a.snapshot,p_answers) then raise exception 'Invalid answers'; end if;
  a.answers:=p_answers;
 end if;
 for q in select value from jsonb_array_elements(a.snapshot) loop
  total:=total+(q->>'marks')::int;
  if a.answers->>(q->>'id')=q->>'correct_option' then earned:=earned+(q->>'marks')::int; correct:=correct+1; end if;
 end loop;
 insert into public.results(id,user_id,test_id,score,total_marks,correct_count,question_count) values(a.id,a.user_id,a.test_id,earned,total,correct,jsonb_array_length(a.snapshot));
 update private.attempts set submitted_at=now(),answers=a.answers where id=a.id;
 return a.id;
end $$;
revoke all on function public.start_attempt(bigint), public.save_answers(uuid,jsonb), public.submit_attempt(uuid,jsonb),public.is_admin() from public,anon;
grant execute on function public.start_attempt(bigint), public.save_answers(uuid,jsonb), public.submit_attempt(uuid,jsonb) to authenticated;
grant execute on function public.is_admin() to anon,authenticated;
-- Optional question illustrations; admin uploads only, public read.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('question-images','question-images',true,2097152,array['image/png','image/jpeg','image/webp']) on conflict do nothing;
create policy question_images_read on storage.objects for select using(bucket_id='question-images');
create policy question_images_admin on storage.objects for all to authenticated using(bucket_id='question-images' and public.is_admin()) with check(bucket_id='question-images' and public.is_admin());
commit;
